baseURL = "https://tsjb.photo/"
languageCode = "en-us"
title = "tsjb.photo"

[menu]
  [[menu.main]]
    identifier = "top"
    name = "Gallery"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "gear"
    name = "Gear"
    url = "/gear/"
    weight = 3
